/**
 * Manifeste « Comprendre la politique » — index léger de TOUT le contenu publié.
 * C'est la seule source de vérité pour l'UI : une page absente d'ici n'existe pas.
 * Le corps des fiches est chargé en lazy (load()) → code-splitting par Vite.
 *
 * Voir docs/jyconnaisrien/05-architecture-technique.md.
 */

export const SECTIONS = {
  bases:                { fr: 'Les bases' },
  familles:             { fr: 'Les familles politiques' },
  partis:               { fr: 'Les partis' },
  figures:              { fr: 'Les personnalités' },
  presidents:           { fr: 'Les présidents' },
  'premiers-ministres': { fr: 'Les Premiers ministres' },
  institutions:         { fr: 'Les institutions' },
  debats:               { fr: 'Les grands débats' },
  dico:                 { fr: 'Le dictionnaire' },
  methodes:             { fr: 'Comment le sait-on ?' },
};

export const LEARN_MANIFEST = [
  {
    slug: 'oqtf',
    section: 'debats',
    type: 'debat',
    title: { fr: `L'OQTF`, en: 'OQTF' },
    hook: { fr: `Décision administrative, pas condamnation pénale : qui décide, qui est protégé, pourquoi tant ne sont pas exécutées — et ce que chaque camp propose.` },
    icon: '📄',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2, 3],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi une oqtf`, `obligation de quitter le territoire`, `oqtf expulsion`, `pourquoi les oqtf ne sont pas exécutées`, `taux d'exécution oqtf`] },
    load: () => import('./debats/oqtf.js').then(m => m.default),
  },
  {
    slug: 'president-de-la-republique',
    section: 'institutions',
    type: 'institution',
    title: { fr: `Le président de la République`, en: 'The President of the Republic' },
    hook: { fr: `Ce qu'il peut faire, ce qu'il ne peut pas faire — et pourquoi il est si puissant… quand il a une majorité.` },
    icon: '🏛️',
    difficulty: 1,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3],
    langs: ['fr'],
    aliases: { fr: [`à quoi sert le président`, `pouvoirs du président`, `pourquoi le président peut dissoudre l'assemblée`, `cohabitation`, `destitution`, `article 16`, `chef de l'état`] },
    load: () => import('./institutions/president-de-la-republique.js').then(m => m.default),
  },
  {
    slug: 'francois-mitterrand',
    section: 'presidents',
    type: 'president',
    title: { fr: `François Mitterrand`, en: 'François Mitterrand' },
    hook: { fr: `1981-1995 : l'alternance, l'abolition, le tournant de 1983, Maastricht — quatorze années qui divisent encore.` },
    icon: '🌹',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`mitterrand`, `qu'a fait mitterrand`, `10 mai 1981`, `tournant de la rigueur`, `abolition de la peine de mort`, `bilan mitterrand`] },
    load: () => import('./presidents/francois-mitterrand.js').then(m => m.default),
  },
  {
    slug: 'charles-de-gaulle',
    section: 'presidents',
    type: 'president',
    title: { fr: `Charles de Gaulle`, en: `Charles de Gaulle` },
    hook: { fr: `1959-1969 : le fondateur — les institutions, l'Algérie, l'indépendance nationale, Mai 68, et un départ sur référendum perdu.` },
    icon: '🇫🇷',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`de gaulle`, `qu'a fait de gaulle`, `guerre d'algérie`, `mai 68`, `fondateur ve république`, `appel du 18 juin`] },
    load: () => import('./presidents/charles-de-gaulle.js').then(m => m.default),
  },
  {
    slug: 'georges-pompidou',
    section: 'presidents',
    type: 'president',
    title: { fr: `Georges Pompidou`, en: `Georges Pompidou` },
    hook: { fr: `1969-1974 : l'impératif industriel — SMIC, Airbus, l'Europe rouverte au Royaume-Uni, et une mort en fonction.` },
    icon: '🏭',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`pompidou`, `qu'a fait pompidou`, `centre pompidou`, `beaubourg`, `smic création`, `loi 1973 banque de france`] },
    load: () => import('./presidents/georges-pompidou.js').then(m => m.default),
  },
  {
    slug: 'valery-giscard-destaing',
    section: 'presidents',
    type: 'president',
    title: { fr: `Valéry Giscard d'Estaing`, en: `Valéry Giscard d'Estaing` },
    hook: { fr: `1974-1981 : la droite libérale qui réforme la société — majorité à 18 ans, loi Veil, divorce, G7 — rattrapée par les chocs pétroliers.` },
    icon: '💠',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`giscard`, `vge`, `giscard d'estaing`, `loi veil`, `majorité 18 ans`, `affaire des diamants`] },
    load: () => import('./presidents/valery-giscard-destaing.js').then(m => m.default),
  },
  {
    slug: 'jacques-chirac',
    section: 'presidents',
    type: 'president',
    title: { fr: `Jacques Chirac`, en: `Jacques Chirac` },
    hook: { fr: `1995-2007 : fracture sociale, Vél d'Hiv, dissolution ratée, non à la guerre d'Irak, non de 2005 — douze ans de paradoxes.` },
    icon: '🍏',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`chirac`, `qu'a fait chirac`, `vel d'hiv`, `guerre d'irak`, `21 avril 2002`, `référendum 2005`, `fracture sociale`] },
    load: () => import('./presidents/jacques-chirac.js').then(m => m.default),
  },
  {
    slug: 'nicolas-sarkozy',
    section: 'presidents',
    type: 'president',
    title: { fr: `Nicolas Sarkozy`, en: `Nicolas Sarkozy` },
    hook: { fr: `2007-2012 : la rupture, la crise financière mondiale, la retraite à 62 ans — et l'hyperprésidence.` },
    icon: '⚡',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`sarkozy`, `qu'a fait sarkozy`, `travailler plus pour gagner plus`, `retraite 62 ans`, `crise 2008`, `bouclier fiscal`] },
    load: () => import('./presidents/nicolas-sarkozy.js').then(m => m.default),
  },
  {
    slug: 'francois-hollande',
    section: 'presidents',
    type: 'president',
    title: { fr: `François Hollande`, en: `François Hollande` },
    hook: { fr: `2012-2017 : mariage pour tous, tournant pro-entreprises, attentats de 2015, COP21 — et un renoncement unique dans la Ve.` },
    icon: '🤝',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`hollande`, `qu'a vraiment fait françois hollande`, `mariage pour tous`, `cice`, `attentats 2015`, `inversion de la courbe`] },
    load: () => import('./presidents/francois-hollande.js').then(m => m.default),
  },
  {
    slug: 'emmanuel-macron',
    section: 'presidents',
    type: 'president',
    title: { fr: `Emmanuel Macron`, en: `Emmanuel Macron` },
    hook: { fr: `Depuis 2017 : la recomposition politique, les gilets jaunes, le Covid, la retraite à 64 ans, la dissolution de 2024 — bilan provisoire, mandat en cours.` },
    icon: '🚶',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`macron`, `qu'a fait macron`, `gilets jaunes`, `dissolution 2024`, `isf ifi`, `retraite 64 ans`, `quoi qu'il en coûte`] },
    load: () => import('./presidents/emmanuel-macron.js').then(m => m.default),
  },
  {
    slug: 'gauche',
    section: 'familles',
    type: 'ideologie',
    title: { fr: `La gauche`, en: `La gauche` },
    hook: { fr: `Égalité, solidarité, services publics… et de nombreuses gauches, de la révolution au réformisme. Le dossier complet.` },
    icon: '📕',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi la gauche`, `être de gauche`, `les gauches`, `socialisme communisme différence`, `front populaire`, `gauche radicale`] },
    load: () => import('./familles/gauche.js').then(m => m.default),
  },
  {
    slug: 'extreme-droite',
    section: 'familles',
    type: 'ideologie',
    title: { fr: `L'extrême droite`, en: `L'extrême droite` },
    hook: { fr: `Critères de classement, histoire, débats : comprendre une catégorie de science politique au lieu de subir le slogan.` },
    icon: '📓',
    difficulty: 3,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`extrême droite`, `rn extrême droite`, `différence droite extrême droite`, `front national histoire`, `droite radicale`] },
    load: () => import('./familles/extreme-droite.js').then(m => m.default),
  },
  {
    slug: 'extreme-gauche',
    section: 'familles',
    type: 'ideologie',
    title: { fr: `L'extrême gauche`, en: `L'extrême gauche` },
    hook: { fr: `Trotskisme, communisme révolutionnaire, anarchisme — et pourquoi LFI n'en fait pas partie pour la plupart des politistes.` },
    icon: '📔',
    difficulty: 3,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`extrême gauche`, `trotskisme`, `lutte ouvrière`, `npa`, `lfi extrême gauche`] },
    load: () => import('./familles/extreme-gauche.js').then(m => m.default),
  },
  {
    slug: 'centre',
    section: 'familles',
    type: 'ideologie',
    title: { fr: `Le centre`, en: `Le centre` },
    hook: { fr: `Ni neutre ni sans opinion : démocratie chrétienne, radicalisme, libéralisme social — une vraie tradition politique.` },
    icon: '📙',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi le centre`, `être centriste`, `centrisme`, `bayrou`, `démocratie chrétienne`, `modem`] },
    load: () => import('./familles/centre.js').then(m => m.default),
  },
  {
    slug: 'immigration',
    section: 'debats',
    type: 'debat',
    title: { fr: `L'immigration`, en: `L'immigration` },
    hook: { fr: `Qui vient, combien, pour quoi faire : les chiffres sourcés, le droit réel, l'état de la recherche — et ce que chaque camp propose.` },
    icon: '🌍',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`immigration en france`, `combien d'immigrés en france`, `l'immigration coûte-t-elle`, `différence immigré étranger`, `solde migratoire`] },
    load: () => import('./debats/immigration.js').then(m => m.default),
  },
  {
    slug: 'laicite',
    section: 'debats',
    type: 'debat',
    title: { fr: `La laïcité`, en: `La laïcité` },
    hook: { fr: `Ce que dit vraiment la loi de 1905, qui doit être neutre et qui ne l'est pas — et pourquoi tout le monde s'en réclame.` },
    icon: '🕊️',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi la laïcité`, `loi 1905`, `laïcité école`, `voile laïcité`, `alsace moselle concordat`] },
    load: () => import('./debats/laicite.js').then(m => m.default),
  },
  {
    slug: 'union-europeenne',
    section: 'debats',
    type: 'debat',
    title: { fr: `L'Union européenne`, en: `L'Union européenne` },
    hook: { fr: `Qui décide quoi à Bruxelles, ce que l'UE peut et ne peut pas faire — et les visions qui s'affrontent depuis Maastricht.` },
    icon: '🇪🇺',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi l'union européenne`, `qui décide en europe`, `commission européenne`, `80 % des lois`, `frexit`, `maastricht`] },
    load: () => import('./debats/union-europeenne.js').then(m => m.default),
  },
  {
    slug: 'assemblee-nationale',
    section: 'institutions',
    type: 'institution',
    title: { fr: `L'Assemblée nationale`, en: `L'Assemblée nationale` },
    hook: { fr: `577 députés qui votent les lois et peuvent renverser le gouvernement — comment ça marche vraiment, navette et 49.3 compris.` },
    icon: '🏟️',
    difficulty: 1,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`assemblée nationale`, `à quoi servent les députés`, `comment une loi est votée`, `navette parlementaire`, `députés`] },
    load: () => import('./institutions/assemblee-nationale.js').then(m => m.default),
  },
  {
    slug: 'conseil-constitutionnel',
    section: 'institutions',
    type: 'institution',
    title: { fr: `Le Conseil constitutionnel`, en: `Le Conseil constitutionnel` },
    hook: { fr: `Les neuf personnes qui peuvent écarter une loi votée — pourquoi c'est voulu, et pourquoi ça fait débat.` },
    icon: '⚖️',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`conseil constitutionnel`, `qpc`, `censure d'une loi`, `sages`, `gouvernement des juges`] },
    load: () => import('./institutions/conseil-constitutionnel.js').then(m => m.default),
  },
  {
    slug: 'elections',
    section: 'bases',
    type: 'fiche-base',
    title: { fr: `Les élections`, en: `Les élections` },
    hook: { fr: `Qui vote, comment, pour quels scrutins — parrainages, financement, sondages, abstention : le mode d'emploi complet.` },
    icon: '🗳️',
    difficulty: 1,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`comment on vote en france`, `les élections`, `vote blanc`, `parrainages`, `procuration`, `abstention`] },
    load: () => import('./bases/elections.js').then(m => m.default),
  },
  {
    slug: 'inflation',
    section: 'debats',
    type: 'debat',
    title: { fr: `L'inflation`, en: 'Inflation' },
    hook: { fr: `D'où viennent les hausses de prix, qui elles frappent, ce que peut vraiment un gouvernement — et pourquoi les prix ne « redescendent » pas.` },
    icon: '💶',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2, 3],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi l'inflation`, `hausse des prix`, `pouvoir d'achat`, `pourquoi tout augmente`, `déflation`, `désinflation`, `bouclier tarifaire`] },
    load: () => import('./debats/inflation.js').then(m => m.default),
  },
  {
    slug: 'droite',
    section: 'familles',
    type: 'ideologie',
    title: { fr: `La droite`, en: 'The Right' },
    hook: { fr: `Ordre, mérite, marché… et au moins huit droites différentes. Le dossier complet.` },
    icon: '📘',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2, 3, 4],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi la droite`, `être de droite`, `les droites`, `droite politique`, `différence droite extrême droite`, `gaullisme`, `conservateur`, `libéral`] },
    load: () => import('./familles/droite.js').then(m => m.default),
  },
  {
    slug: 'retraites',
    section: 'debats',
    type: 'debat',
    title: { fr: `Les retraites`, en: 'Pensions' },
    hook: { fr: `Pourquoi ce débat revient à chaque élection — répartition, démographie, et trois visions qui s'affrontent.` },
    icon: '🧓',
    difficulty: 2,
    famille: 'dossier',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2, 3],
    langs: ['fr'],
    aliases: { fr: [`réforme des retraites`, `âge de départ`, `64 ans`, `répartition`, `pension`] },
    load: () => import('./debats/retraites.js').then(m => m.default),
  },
  {
    slug: 'oqtf',
    section: 'dico',
    categorie: 'immigration',
    type: 'definition',
    searchable: false,
    title: { fr: `L'OQTF`, en: 'OQTF' },
    hook: { fr: `Une décision administrative, pas une condamnation pénale — ce qu'elle est, qui décide, pourquoi toutes ne sont pas exécutées.` },
    icon: '📄',
    difficulty: 2,
    famille: 'intermediaire',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi une oqtf`, `obligation de quitter le territoire`, `oqtf expulsion`, `oqtf définition`] },
    load: () => import('./dico/immigration.js').then(m => m.TERMS['oqtf']),
  },
  {
    slug: '49-3',
    section: 'dico',
    categorie: 'institutions',
    type: 'definition',
    title: { fr: `Le 49.3`, en: 'Article 49.3' },
    hook: { fr: `L'article qui permet d'adopter une loi sans vote — et le bras de fer qu'il déclenche.` },
    icon: '🏛️',
    difficulty: 1,
    famille: 'intermediaire',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi le 49.3`, `49 3`, `quarante-neuf trois`, `article 49 alinéa 3`, `loi sans vote`] },
    load: () => import('./dico/institutions.js').then(m => m.TERMS['49-3']),
  },
  {
    slug: 'motion-de-censure',
    section: 'dico',
    categorie: 'institutions',
    type: 'definition',
    title: { fr: `La motion de censure`, en: 'Motion of no confidence' },
    hook: { fr: `Le vote qui peut faire tomber un gouvernement — comment ça marche, quand ça a réussi.` },
    icon: '🗳️',
    difficulty: 1,
    famille: 'intermediaire',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi une motion de censure`, `renverser le gouvernement`, `censure assemblée`] },
    load: () => import('./dico/institutions.js').then(m => m.TERMS['motion-de-censure']),
  },
  {
    slug: 'proportionnelle',
    section: 'dico',
    categorie: 'institutions',
    type: 'definition',
    title: { fr: `La proportionnelle`, en: 'Proportional representation' },
    hook: { fr: `20 % des voix, 20 % des sièges : le mode de scrutin dont la France débat depuis quarante ans.` },
    icon: '📊',
    difficulty: 1,
    famille: 'court',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'periodic',
    hasLevels: [1, 2],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi la proportionnelle`, `scrutin proportionnel`, `mode de scrutin`, `proportionnelle législatives`] },
    load: () => import('./dico/institutions.js').then(m => m.TERMS['proportionnelle']),
  },
  {
    slug: 'dette-publique',
    section: 'dico',
    categorie: 'economie',
    type: 'definition',
    title: { fr: `La dette publique`, en: 'Public debt' },
    hook: { fr: `Plus de 3 000 milliards d'euros : ce que c'est vraiment, et pourquoi les économistes ne sont pas d'accord.` },
    icon: '📉',
    difficulty: 1,
    famille: 'intermediaire',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'live',
    hasLevels: [1, 2],
    langs: ['fr'],
    aliases: { fr: [`c'est quoi la dette publique`, `dette de la france`, `3000 milliards`, `dette et déficit`] },
    load: () => import('./dico/economie.js').then(m => m.TERMS['dette-publique']),
  },
  {
    slug: 'economie-de-marche',
    section: 'dico',
    categorie: 'economie',
    type: 'definition',
    title: { fr: `L'économie de marché`, en: 'Market economy' },
    hook: { fr: `Offre, demande, prix — et la vraie question politique : quelle place pour l'État ?` },
    icon: '🏪',
    difficulty: 1,
    famille: 'court',
    updatedAt: '2026-07-12',
    lastReviewedAt: '2026-07-12',
    freshnessType: 'stable',
    hasLevels: [1, 2],
    langs: ['fr'],
    aliases: { fr: [`économie de marché`, `capitalisme`, `marché et état`] },
    load: () => import('./dico/economie.js').then(m => m.TERMS['economie-de-marche']),
  },
];

/** Pages non encore publiées mais annoncées sur le hub (cartes « Bientôt »). */
export const UPCOMING = [
  { slug: 'partis', section: 'partis', title: { fr: `Les partis` }, icon: '🎪', hook: { fr: `Qui est qui : les principaux partis français, un par un.` } },
];

export function findEntry(section, slug) {
  return LEARN_MANIFEST.find(e => e.section === section && e.slug === slug) || null;
}

export function findBySlug(slug) {
  return LEARN_MANIFEST.find(e => e.slug === slug) || null;
}

/** Recherche naïve : normalise, ignore les préfixes de question, score titre + alias + hook. */
const QUESTION_PREFIXES = /^(c'est quoi|c est quoi|qu'est[- ]ce (que|qu'une?|qu'un)|pourquoi|comment|quelle? (différence|est la différence) entre|définition( de)?|explique[rz]?( moi)?)\s+/i;

function normalize(s) {
  return (s || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[«»"'’,?!.]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function searchLearn(query, { limit = 6 } = {}) {
  const q = normalize(query).replace(QUESTION_PREFIXES, '').replace(/^(la |le |les |l |une? |des |du |de la )/, '').trim();
  if (q.length < 2) return [];
  const tokens = q.split(' ').filter(w => w.length > 1);
  const scored = LEARN_MANIFEST.filter(e => e.searchable !== false).map(entry => {
    const title = normalize(entry.title.fr);
    const aliases = (entry.aliases?.fr || []).map(normalize);
    const hook = normalize(entry.hook?.fr || '');
    let score = 0;
    if (title === q) score += 100;
    if (title.includes(q)) score += 50;
    if (aliases.some(a => a === q)) score += 90;
    if (aliases.some(a => a.includes(q) || q.includes(a))) score += 40;
    for (const tk of tokens) {
      if (title.includes(tk)) score += 12;
      if (aliases.some(a => a.includes(tk))) score += 8;
      if (hook.includes(tk)) score += 3;
    }
    return { entry, score };
  }).filter(r => r.score > 0);
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map(r => r.entry);
}
